name = "two-control-lean"
version = "0.1.0"

[package]
name = "two-control-lean"
version = "0.1.0"

[[lean_lib]]
name = "TwoControl"
defaultTargets = ["TwoControl"]

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
